import { FeathersObject } from "./feathers";

export class DialogData<T> {
  constructor(public response: T) {
  }
}

export class User implements FeathersObject {
  public picture: string;
  public roles: string[];

  constructor(
    public email: string,
    public password: string,
    public about?: string,
  ) {}

  public _id: string;
  public createdAt: string;
  public updatedAt: string;
}

export class Image implements FeathersObject{
  public path: string;
  public data: string;

  constructor(
    public name: string,
    public author: string,
    public about?: string,
    public tags?: string[],
  ) {}

// generated by API
  public _id: string;
  public createdAt: string;
  public updatedAt: string;
}

export class ImageCommentary implements FeathersObject {
  constructor(
    public author: string,
    public imageId: string,
    public content: string,
  ) {}

  public _id: string;
  public createdAt: string;
  public updatedAt: string;
}

export class ImageFile {
  public id: string;
  public uri: string;
}

export class Likes implements FeathersObject {
  constructor (
    public authorId: string,
    public imageId: string,
) {}

  public _id: string;
  public createdAt: string;
  public updatedAt: string;
}

export class Tag implements FeathersObject {
  constructor (
    public name: string
  ) {}

  public _id: string;
  public createdAt: string;
  public updatedAt: string;
}

export class Notification implements FeathersObject {
  constructor (
    public type: string,
    public read: boolean,
    public authorId: string,
    public imageId: string,
    public receiver: string,
  ) {}

  public _id: string;
  public createdAt: string;
  public updatedAt: string;
}
